name: Generate Sitemap  

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest  # 运行环境是最新版 Ubuntu
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Generate the sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://worldeditors.github.io/ 

      - name: Commit and push the sitemap
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update"
            git push
          fi